export const SIZE_REFERENCE = Object.freeze({
    DEFAULT_PADDING: 5,
    INNER_TOP_PADDING_Y: 38,
    INNER_BOTTOM_PADDING_Y: 5,
    PADDING_Y: 12,
    PADDING_X: 12,
    MARGIN_Y: 10,
    MARGIN_X: 12,
    DEFAULT_WIDTH: 140,
    DEFAULT_HEIGHT: 50,
    MAX_HORIZONTAL_COUNT: 5,
    MAX_CHILD_HORIZONTAL_COUNT: 2,
    SMALL_SIZE_INCREMENT: 1,
    MEDIUM_SIZE_INCREMENT: 2,
    LARGE_SIZE_INCREMENT: 4,
    X_LARGE_SIZE_INCREMENT: 8,
    HUGE_SIZE_INCREMENT: 16,
    OTHER_SIZE_INCREMENT: 32
});